const BattleMap = require('./BattleMap.js')
const Engine = require('./Engine.js')

e = new Engine()
e.add_player(1, 2, 2)
e.add_player(2, 5, 5)
e.add_player(3)
e.add_player(4)

e.invade(1, 2, 3)
e.battleMap.decline_all_strength()
e.invade(1, 2, 4)
e.battleMap.decline_all_strength()
e.invade(1, 1, 2)
e.battleMap.decline_all_strength()
e.invade(1, 1, 2)
e.battleMap.decline_all_strength()
e.invade(1, 4, 7)
e.battleMap.render()
e.battleMap.decline_all_strength()

e.invade(2, 4, 5)
e.invade(2, 5, 6)
e.battleMap.render()
